### ISSUE TITLE
Wrong linux lib name

### ISSUE THREAD

**Issue by gpav3l** [AktivCo/pkcs11_for_dummies#1]
I'm found, that CMakeList.txt in root folder have mistype in library name for linux machine, need change in line 29 from rtpkcs11ecp.so to librtpkcs11ecp.so, in other case library will not be found and downloaded, so all executed example will be failed.

**Comment by UlrichVonRekkenin** [comment]
> I'm found, that CMakeList.txt in root folder have mistype in library name for linux machine, need change in line 29 from rtpkcs11ecp.so to librtpkcs11ecp.so, in other case library will not be found and downloaded, so all executed example will be failed.

I'd better say, for linux system change [this](https://github.com/AktivCo/pkcs11_for_dummies/blob/master/src/include/win2nix.h#L39) line for `"librtpkcs11ecp.so"`.

**Comment by Mironenko** [comment]
> > I'm found, that CMakeList.txt in root folder have mistype in library name for linux machine, need change in line 29 from rtpkcs11ecp.so to librtpkcs11ecp.so, in other case library will not be found and downloaded, so all executed example will be failed.
> 
> I'd better say, for linux system change [this](https://github.com/AktivCo/pkcs11_for_dummies/blob/master/src/include/win2nix.h#L39) line for `"librtpkcs11ecp.so"`.

There is no problem with the loading of the library, see definitions in [Common.h](https://github.com/AktivCo/pkcs11_for_dummies/blob/650ecb496f7f80ba2bd22659e4a92f63889d2bca/src/include/Common.h#L41)
